# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbab72308e1263046ea2d525d4528fa6d1e93444e18919f3c0a6ef42e3e67fb5548303dfd3301504c6177cb17f56f7b44ca30c85df6e74db391642cb9241f0f1
  google_key: "74193557966-8m2t1j7u9eb5jd6fqidgbev6632j6ftl.apps.googleusercontent.com"
  client_key: "-Gq2Kl5-fKSuKgBtJfChOGlR"

test:
  secret_key_base: aaa0422cff6948d3f4b772077e8d31e064ad3affe238061a9b40776b94954803b51112aaccd2df37cd054b7cc24216842a007e2b29758221ac4359afca208496
  google_key: "74193557966-8m2t1j7u9eb5jd6fqidgbev6632j6ftl.apps.googleusercontent.com"
  client_key: "-Gq2Kl5-fKSuKgBtJfChOGlR"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_key: "74193557966-8m2t1j7u9eb5jd6fqidgbev6632j6ftl.apps.googleusercontent.com"
  client_key: "-Gq2Kl5-fKSuKgBtJfChOGlR"
